//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using practice.HelperClasses;
using practice.FactoryClasses;
using practice.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace practice.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Manager'.<br/><br/></summary>
	[Serializable]
	public partial class ManagerEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<EmployeeEntity> _employees;
		private DepartmentEntity _department;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ManagerEntityStaticMetaData _staticMetaData = new ManagerEntityStaticMetaData();
		private static ManagerRelations _relationsFactory = new ManagerRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Department</summary>
			public static readonly string Department = "Department";
			/// <summary>Member name Employees</summary>
			public static readonly string Employees = "Employees";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ManagerEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ManagerEntityStaticMetaData()
			{
				SetEntityCoreInfo("ManagerEntity", InheritanceHierarchyType.None, false, (int)practice.EntityType.ManagerEntity, typeof(ManagerEntity), typeof(ManagerEntityFactory), false);
				AddNavigatorMetaData<ManagerEntity, EntityCollection<EmployeeEntity>>("Employees", a => a._employees, (a, b) => a._employees = b, a => a.Employees, () => new ManagerRelations().EmployeeEntityUsingManagerId, typeof(EmployeeEntity), (int)practice.EntityType.EmployeeEntity);
				AddNavigatorMetaData<ManagerEntity, DepartmentEntity>("Department", "Managers", (a, b) => a._department = b, a => a._department, (a, b) => a.Department = b, practice.RelationClasses.StaticManagerRelations.DepartmentEntityUsingDepartmentIdStatic, ()=>new ManagerRelations().DepartmentEntityUsingDepartmentId, null, new int[] { (int)ManagerFieldIndex.DepartmentId }, null, true, (int)practice.EntityType.DepartmentEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ManagerEntity()
		{
		}

		/// <summary> CTor</summary>
		public ManagerEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ManagerEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ManagerEntity</param>
		public ManagerEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Manager which data should be fetched into this Manager object</param>
		public ManagerEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Manager which data should be fetched into this Manager object</param>
		/// <param name="validator">The custom validator object for this ManagerEntity</param>
		public ManagerEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ManagerEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Employee' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoEmployees() { return CreateRelationInfoForNavigator("Employees"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Department' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDepartment() { return CreateRelationInfoForNavigator("Department"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ManagerEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ManagerRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Employee' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathEmployees { get { return _staticMetaData.GetPrefetchPathElement("Employees", CommonEntityBase.CreateEntityCollection<EmployeeEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Department' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDepartment { get { return _staticMetaData.GetPrefetchPathElement("Department", CommonEntityBase.CreateEntityCollection<DepartmentEntity>()); } }

		/// <summary>The DepartmentId property of the Entity Manager<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Managers"."DepartmentId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DepartmentId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ManagerFieldIndex.DepartmentId, false); }
			set	{ SetValue((int)ManagerFieldIndex.DepartmentId, value); }
		}

		/// <summary>The Id property of the Entity Manager<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Managers"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)ManagerFieldIndex.Id, true); }
			set { SetValue((int)ManagerFieldIndex.Id, value); }		}

		/// <summary>The Name property of the Entity Manager<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Managers"."Name".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 60.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ManagerFieldIndex.Name, true); }
			set	{ SetValue((int)ManagerFieldIndex.Name, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'EmployeeEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(EmployeeEntity))]
		public virtual EntityCollection<EmployeeEntity> Employees { get { return GetOrCreateEntityCollection<EmployeeEntity, EmployeeEntityFactory>("Manager", true, false, ref _employees); } }

		/// <summary>Gets / sets related entity of type 'DepartmentEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual DepartmentEntity Department
		{
			get { return _department; }
			set { SetSingleRelatedEntityNavigator(value, "Department"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace practice
{
	public enum ManagerFieldIndex
	{
		///<summary>DepartmentId. </summary>
		DepartmentId,
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace practice.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Manager. </summary>
	public partial class ManagerRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ManagerEntity and EmployeeEntity over the 1:n relation they have, using the relation between the fields: Manager.Id - Employee.ManagerId</summary>
		public virtual IEntityRelation EmployeeEntityUsingManagerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Employees", true, new[] { ManagerFields.Id, EmployeeFields.ManagerId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ManagerEntity and DepartmentEntity over the m:1 relation they have, using the relation between the fields: Manager.DepartmentId - Department.Id</summary>
		public virtual IEntityRelation DepartmentEntityUsingDepartmentId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Department", false, new[] { DepartmentFields.Id, ManagerFields.DepartmentId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticManagerRelations
	{
		internal static readonly IEntityRelation EmployeeEntityUsingManagerIdStatic = new ManagerRelations().EmployeeEntityUsingManagerId;
		internal static readonly IEntityRelation DepartmentEntityUsingDepartmentIdStatic = new ManagerRelations().DepartmentEntityUsingDepartmentId;

		/// <summary>CTor</summary>
		static StaticManagerRelations() { }
	}
}
