//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace practice.HelperClasses
{
	/// <summary>Field Creation Class for entity DepartmentEntity</summary>
	public partial class DepartmentFields
	{
		/// <summary>Creates a new DepartmentEntity.DepartmentName field instance</summary>
		public static EntityField2 DepartmentName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentFieldIndex.DepartmentName); }}
		/// <summary>Creates a new DepartmentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity EmployeeEntity</summary>
	public partial class EmployeeFields
	{
		/// <summary>Creates a new EmployeeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Id); }}
		/// <summary>Creates a new EmployeeEntity.ManagerId field instance</summary>
		public static EntityField2 ManagerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.ManagerId); }}
		/// <summary>Creates a new EmployeeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity ManagerEntity</summary>
	public partial class ManagerFields
	{
		/// <summary>Creates a new ManagerEntity.DepartmentId field instance</summary>
		public static EntityField2 DepartmentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ManagerFieldIndex.DepartmentId); }}
		/// <summary>Creates a new ManagerEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ManagerFieldIndex.Id); }}
		/// <summary>Creates a new ManagerEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ManagerFieldIndex.Name); }}
	}
	

}