//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace ViewModel.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Manager'.</summary>
	[Serializable]
	[DataContract]
	public partial class ManagerEmployeeViewModel
	{
		/// <summary>Gets or sets the DepartmentId field. Derived from Entity Model Field 'Manager.DepartmentId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> DepartmentId { get; set; }
		/// <summary>Gets or sets the Employees field. </summary>
		[DataMember]
		public List<ManagerEmployeeViewModelTypes.Employee> Employees { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Manager.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Manager.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
	}

	namespace ManagerEmployeeViewModelTypes
	{
		/// <summary> DTO class which is derived from the entity 'Employee (Employees)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Employee
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Employee.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the ManagerId field. Derived from Entity Model Field 'Employee.ManagerId (FK)'</summary>
			[DataMember]
			public Nullable<System.Int32> ManagerId { get; set; }
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Employee.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
		}
	}

}




